version: '3'
services:
  app:
    image: 1372022/app
    ports:
      - "5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: 1372022/nginx
    ports:
      - "80:80"
    depends_on:
      - app